#ifndef __I_ACTIVITY_DAO_H__
#define __I_ACTIVITY_DAO_H__

#include "activity_types.h"
#include <vector>
#include <utility>

class IActivityDao {
public:
    virtual ~IActivityDao() {}

    /**
     * @brief Create a new activity
     * @param info Activity info (id ignored, generated by DB)
     * @param out_id Output: new activity ID
     * @return DB_OK on success, ERR_ACTIVITY_* on validation failure
     */
    virtual int CreateActivity(const ActivityInfo& info, int64_t& out_id) = 0;

    /**
     * @brief Update activity info (excludes status, signup_count, images)
     * @return DB_OK on success, ERR_ACTIVITY_NOT_FOUND if id doesn't exist
     */
    virtual int UpdateActivity(const ActivityInfo& info) = 0;

    /**
     * @brief Delete activity + cascade delete signups (transactional)
     * @return DB_OK on success, ERR_ACTIVITY_NOT_FOUND if id doesn't exist
     */
    virtual int DeleteActivity(int64_t id) = 0;

    /**
     * @brief Get single activity by ID
     * @return DB_OK on success, ERR_ACTIVITY_NOT_FOUND if not found
     */
    virtual int GetActivity(int64_t id, ActivityInfo& info) = 0;

    /**
     * @brief List all activities (admin), ordered by sort_order ASC
     */
    virtual int ListActivities(std::vector<ActivityInfo>& list) = 0;

    /**
     * @brief List published activities only (public), ordered by sort_order ASC
     */
    virtual int ListPublishedActivities(std::vector<ActivityInfo>& list) = 0;

    /**
     * @brief List published activities with pagination
     * @param list Output list of activities
     * @param limit Maximum number of records to return
     * @param offset Number of records to skip
     * @param total_count Output total number of published activities
     */
    virtual int ListPublishedActivitiesPaged(std::vector<ActivityInfo>& list, int limit, int offset, int& total_count) = 0;

    /**
     * @brief Update publish status
     */
    virtual int UpdateActivityStatus(int64_t id, int32_t status) = 0;

    /**
     * @brief Update cover_image or group_image path
     * @param field "cover_image" or "group_image"
     */
    virtual int UpdateActivityImage(int64_t id, const std::string& field,
                                    const std::string& path) = 0;

    /**
     * @brief Increment signup_count by 1
     */
    virtual int IncrementSignupCount(int64_t id) = 0;

    /**
     * @brief Increment signup_count by delta (for group confirm)
     */
    virtual int BatchIncrementSignupCount(int64_t id, int32_t delta) = 0;

    /**
     * @brief Batch update sort_order (transactional)
     * @param orders Vector of (activity_id, sort_order) pairs
     */
    virtual int BatchUpdateSortOrder(
        const std::vector<std::pair<int64_t, int32_t>>& orders) = 0;

    virtual int AddCoverImage(int64_t activity_id, const std::string& path,
                              int sort_order, int64_t& out_id) = 0;

    virtual int GetCoverImages(int64_t activity_id,
                               std::vector<ActivityCoverImage>& images) = 0;

    virtual int DeleteCoverImage(int64_t image_id) = 0;

    virtual int DeleteCoverImagesByActivityId(int64_t activity_id) = 0;

    virtual int AddPromotionImage(const std::string& path, int sort_order,
                                  int64_t& out_id) = 0;
    virtual int GetPromotionImages(std::vector<ActivityCoverImage>& images) = 0;
    virtual int DeletePromotionImage(int64_t image_id) = 0;
    virtual int BatchUpdatePromotionImageSortOrder(
        const std::vector<std::pair<int64_t, int32_t>>& orders) = 0;
    virtual int GetPromotionText(std::string& content) = 0;
    virtual int UpdatePromotionText(const std::string& content) = 0;

    virtual int GetActivityNotice(std::string& content) = 0;
    virtual int UpdateActivityNotice(const std::string& content) = 0;

    virtual int AddAboutUsCard(const std::string& image_path,
                               const std::string& text, int32_t layout_type,
                               int32_t sort_order, int64_t& out_id) = 0;
    virtual int GetAboutUsCards(std::vector<AboutUsCard>& cards) = 0;
    virtual int UpdateAboutUsCard(int64_t id, const std::string& image_path,
                                  const std::string& text,
                                  int32_t layout_type) = 0;
    virtual int DeleteAboutUsCard(int64_t card_id) = 0;
    virtual int BatchUpdateAboutUsCardSortOrder(
        const std::vector<std::pair<int64_t, int32_t>>& orders) = 0;
};

#endif /* __I_ACTIVITY_DAO_H__ */
